package defpackage;

import androidx.emoji2.text.Fk.Iyrs;
import com.google.android.material.card.ZyJo.nTAZxGMqQtZZAQ;
import flar2.devcheck.usage.GgP.rlfWzcx;

/* loaded from: classes.dex */
public abstract class li2 {

    /* renamed from: a, reason: collision with root package name */
    public static final qj f593a;
    public static final qj b;
    public static final qj c;
    public static final qj d;
    public static final qj e;
    public static final qj f;
    public static final qj g;
    public static final qj h;
    public static final qj i;
    public static final qj j;
    public static final qj k;
    public static final qj l;
    public static final qj m;
    public static final qj n;
    public static final qj o;
    public static final qj p;
    public static final qj q;
    public static final qj r;
    public static final qj s;
    public static final qj t;

    static {
        cf a2 = qj.a();
        a2.f122a = 3;
        a2.b = nTAZxGMqQtZZAQ.CHxErBkAoK;
        f593a = a2.a();
        cf a3 = qj.a();
        a3.f122a = 3;
        a3.b = "Google Play In-app Billing API version is less than 9";
        b = a3.a();
        cf a4 = qj.a();
        a4.f122a = 3;
        String str = Iyrs.tyTrDvfJjdVlmGn;
        a4.b = str;
        c = a4.a();
        cf a5 = qj.a();
        a5.f122a = 2;
        a5.b = str;
        d = a5.a();
        cf a6 = qj.a();
        a6.f122a = 5;
        a6.b = "Client is already in the process of connecting to billing service.";
        e = a6.a();
        cf a7 = qj.a();
        a7.f122a = 5;
        a7.b = "The list of SKUs can't be empty.";
        a7.a();
        cf a8 = qj.a();
        a8.f122a = 5;
        a8.b = "SKU type can't be empty.";
        a8.a();
        cf a9 = qj.a();
        a9.f122a = 5;
        a9.b = "Product type can't be empty.";
        f = a9.a();
        cf a10 = qj.a();
        a10.f122a = -2;
        a10.b = "Client does not support extra params.";
        g = a10.a();
        cf a11 = qj.a();
        a11.f122a = 5;
        a11.b = "Invalid purchase token.";
        h = a11.a();
        cf a12 = qj.a();
        a12.f122a = 6;
        a12.b = "An internal error occurred.";
        i = a12.a();
        cf a13 = qj.a();
        a13.f122a = 5;
        a13.b = "SKU can't be null.";
        a13.a();
        cf a14 = qj.a();
        a14.f122a = 0;
        j = a14.a();
        cf a15 = qj.a();
        a15.f122a = -1;
        a15.b = "Service connection is disconnected.";
        k = a15.a();
        cf a16 = qj.a();
        a16.f122a = 2;
        a16.b = "Timeout communicating with service.";
        l = a16.a();
        cf a17 = qj.a();
        a17.f122a = -2;
        a17.b = rlfWzcx.iXIUANml;
        m = a17.a();
        cf a18 = qj.a();
        a18.f122a = -2;
        a18.b = "Client does not support subscriptions update.";
        a18.a();
        cf a19 = qj.a();
        a19.f122a = -2;
        a19.b = "Client does not support get purchase history.";
        n = a19.a();
        cf a20 = qj.a();
        a20.f122a = -2;
        a20.b = "Client does not support price change confirmation.";
        a20.a();
        cf a21 = qj.a();
        a21.f122a = -2;
        a21.b = "Play Store version installed does not support cross selling products.";
        a21.a();
        cf a22 = qj.a();
        a22.f122a = -2;
        a22.b = "Client does not support multi-item purchases.";
        o = a22.a();
        cf a23 = qj.a();
        a23.f122a = -2;
        a23.b = "Client does not support offer_id_token.";
        p = a23.a();
        cf a24 = qj.a();
        a24.f122a = -2;
        a24.b = "Client does not support ProductDetails.";
        q = a24.a();
        cf a25 = qj.a();
        a25.f122a = -2;
        a25.b = "Client does not support in-app messages.";
        a25.a();
        cf a26 = qj.a();
        a26.f122a = -2;
        a26.b = "Client does not support user choice billing.";
        a26.a();
        cf a27 = qj.a();
        a27.f122a = -2;
        a27.b = "Play Store version installed does not support external offer.";
        a27.a();
        cf a28 = qj.a();
        a28.f122a = -2;
        a28.b = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a28.a();
        cf a29 = qj.a();
        a29.f122a = 5;
        a29.b = "Unknown feature";
        a29.a();
        cf a30 = qj.a();
        a30.f122a = -2;
        a30.b = "Play Store version installed does not support get billing config.";
        a30.a();
        cf a31 = qj.a();
        a31.f122a = -2;
        a31.b = "Query product details with serialized docid is not supported.";
        a31.a();
        cf a32 = qj.a();
        a32.f122a = 4;
        a32.b = "Item is unavailable for purchase.";
        r = a32.a();
        cf a33 = qj.a();
        a33.f122a = -2;
        a33.b = "Query product details with developer specified account is not supported.";
        a33.a();
        cf a34 = qj.a();
        a34.f122a = -2;
        a34.b = "Play Store version installed does not support alternative billing only.";
        a34.a();
        cf a35 = qj.a();
        a35.f122a = 5;
        a35.b = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        s = a35.a();
        cf a36 = qj.a();
        a36.f122a = 6;
        a36.b = "An error occurred while retrieving billing override.";
        t = a36.a();
    }

    public static qj a(int i2, String str) {
        cf a2 = qj.a();
        a2.f122a = i2;
        a2.b = str;
        return a2.a();
    }
}
