package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* loaded from: classes.dex */
public final class ov {

    /* renamed from: a, reason: collision with root package name */
    public int f760a;
    public final rv b;
    public final qv c;
    public final pv d;
    public final sv e;
    public HashMap f;

    public ov() {
        rv rvVar = new rv();
        rvVar.f909a = 0;
        rvVar.b = 0;
        rvVar.c = 1.0f;
        rvVar.d = Float.NaN;
        this.b = rvVar;
        qv qvVar = new qv();
        qvVar.f863a = -1;
        qvVar.b = 0;
        qvVar.c = -1;
        qvVar.d = Float.NaN;
        qvVar.e = Float.NaN;
        qvVar.f = Float.NaN;
        qvVar.g = -1;
        qvVar.h = null;
        qvVar.i = -1;
        this.c = qvVar;
        pv pvVar = new pv();
        pvVar.f810a = false;
        pvVar.d = -1;
        pvVar.e = -1;
        pvVar.f = -1.0f;
        pvVar.g = true;
        pvVar.h = -1;
        pvVar.i = -1;
        pvVar.j = -1;
        pvVar.k = -1;
        pvVar.l = -1;
        pvVar.m = -1;
        pvVar.n = -1;
        pvVar.o = -1;
        pvVar.p = -1;
        pvVar.q = -1;
        pvVar.r = -1;
        pvVar.s = -1;
        pvVar.t = -1;
        pvVar.u = -1;
        pvVar.v = -1;
        pvVar.w = 0.5f;
        pvVar.x = 0.5f;
        pvVar.y = null;
        pvVar.z = -1;
        pvVar.A = 0;
        pvVar.B = 0.0f;
        pvVar.C = -1;
        pvVar.D = -1;
        pvVar.E = -1;
        pvVar.F = 0;
        pvVar.G = 0;
        pvVar.H = 0;
        pvVar.I = 0;
        pvVar.J = 0;
        pvVar.K = 0;
        pvVar.L = 0;
        pvVar.M = Integer.MIN_VALUE;
        pvVar.N = Integer.MIN_VALUE;
        pvVar.O = Integer.MIN_VALUE;
        pvVar.P = Integer.MIN_VALUE;
        pvVar.Q = Integer.MIN_VALUE;
        pvVar.R = Integer.MIN_VALUE;
        pvVar.S = Integer.MIN_VALUE;
        pvVar.T = -1.0f;
        pvVar.U = -1.0f;
        pvVar.V = 0;
        pvVar.W = 0;
        pvVar.X = 0;
        pvVar.Y = 0;
        pvVar.Z = 0;
        pvVar.a0 = 0;
        pvVar.b0 = 0;
        pvVar.c0 = 0;
        pvVar.d0 = 1.0f;
        pvVar.e0 = 1.0f;
        pvVar.f0 = -1;
        pvVar.g0 = 0;
        pvVar.h0 = -1;
        pvVar.l0 = false;
        pvVar.m0 = false;
        pvVar.n0 = true;
        pvVar.o0 = 0;
        this.d = pvVar;
        sv svVar = new sv();
        svVar.f956a = 0.0f;
        svVar.b = 0.0f;
        svVar.c = 0.0f;
        svVar.d = 1.0f;
        svVar.e = 1.0f;
        svVar.f = Float.NaN;
        svVar.g = Float.NaN;
        svVar.h = -1;
        svVar.i = 0.0f;
        svVar.j = 0.0f;
        svVar.k = 0.0f;
        svVar.l = false;
        svVar.m = 0.0f;
        this.e = svVar;
        this.f = new HashMap();
    }

    public final void a(jv jvVar) {
        pv pvVar = this.d;
        jvVar.e = pvVar.h;
        jvVar.f = pvVar.i;
        jvVar.g = pvVar.j;
        jvVar.h = pvVar.k;
        jvVar.i = pvVar.l;
        jvVar.j = pvVar.m;
        jvVar.k = pvVar.n;
        jvVar.l = pvVar.o;
        jvVar.m = pvVar.p;
        jvVar.n = pvVar.q;
        jvVar.o = pvVar.r;
        jvVar.s = pvVar.s;
        jvVar.t = pvVar.t;
        jvVar.u = pvVar.u;
        jvVar.v = pvVar.v;
        ((ViewGroup.MarginLayoutParams) jvVar).leftMargin = pvVar.F;
        ((ViewGroup.MarginLayoutParams) jvVar).rightMargin = pvVar.G;
        ((ViewGroup.MarginLayoutParams) jvVar).topMargin = pvVar.H;
        ((ViewGroup.MarginLayoutParams) jvVar).bottomMargin = pvVar.I;
        jvVar.A = pvVar.R;
        jvVar.B = pvVar.Q;
        jvVar.x = pvVar.N;
        jvVar.z = pvVar.P;
        jvVar.E = pvVar.w;
        jvVar.F = pvVar.x;
        jvVar.p = pvVar.z;
        jvVar.q = pvVar.A;
        jvVar.r = pvVar.B;
        jvVar.G = pvVar.y;
        jvVar.T = pvVar.C;
        jvVar.U = pvVar.D;
        jvVar.I = pvVar.T;
        jvVar.H = pvVar.U;
        jvVar.K = pvVar.W;
        jvVar.J = pvVar.V;
        jvVar.W = pvVar.l0;
        jvVar.X = pvVar.m0;
        jvVar.L = pvVar.X;
        jvVar.M = pvVar.Y;
        jvVar.P = pvVar.Z;
        jvVar.Q = pvVar.a0;
        jvVar.N = pvVar.b0;
        jvVar.O = pvVar.c0;
        jvVar.R = pvVar.d0;
        jvVar.S = pvVar.e0;
        jvVar.V = pvVar.E;
        jvVar.c = pvVar.f;
        jvVar.f498a = pvVar.d;
        jvVar.b = pvVar.e;
        ((ViewGroup.MarginLayoutParams) jvVar).width = pvVar.b;
        ((ViewGroup.MarginLayoutParams) jvVar).height = pvVar.c;
        String str = pvVar.k0;
        if (str != null) {
            jvVar.Y = str;
        }
        jvVar.Z = pvVar.o0;
        jvVar.setMarginStart(pvVar.K);
        jvVar.setMarginEnd(pvVar.J);
        jvVar.a();
    }

    public final Object clone() {
        ov ovVar = new ov();
        pv pvVar = ovVar.d;
        pvVar.getClass();
        pv pvVar2 = this.d;
        pvVar.f810a = pvVar2.f810a;
        pvVar.b = pvVar2.b;
        pvVar.c = pvVar2.c;
        pvVar.d = pvVar2.d;
        pvVar.e = pvVar2.e;
        pvVar.f = pvVar2.f;
        pvVar.g = pvVar2.g;
        pvVar.h = pvVar2.h;
        pvVar.i = pvVar2.i;
        pvVar.j = pvVar2.j;
        pvVar.k = pvVar2.k;
        pvVar.l = pvVar2.l;
        pvVar.m = pvVar2.m;
        pvVar.n = pvVar2.n;
        pvVar.o = pvVar2.o;
        pvVar.p = pvVar2.p;
        pvVar.q = pvVar2.q;
        pvVar.r = pvVar2.r;
        pvVar.s = pvVar2.s;
        pvVar.t = pvVar2.t;
        pvVar.u = pvVar2.u;
        pvVar.v = pvVar2.v;
        pvVar.w = pvVar2.w;
        pvVar.x = pvVar2.x;
        pvVar.y = pvVar2.y;
        pvVar.z = pvVar2.z;
        pvVar.A = pvVar2.A;
        pvVar.B = pvVar2.B;
        pvVar.C = pvVar2.C;
        pvVar.D = pvVar2.D;
        pvVar.E = pvVar2.E;
        pvVar.F = pvVar2.F;
        pvVar.G = pvVar2.G;
        pvVar.H = pvVar2.H;
        pvVar.I = pvVar2.I;
        pvVar.J = pvVar2.J;
        pvVar.K = pvVar2.K;
        pvVar.L = pvVar2.L;
        pvVar.M = pvVar2.M;
        pvVar.N = pvVar2.N;
        pvVar.O = pvVar2.O;
        pvVar.P = pvVar2.P;
        pvVar.Q = pvVar2.Q;
        pvVar.R = pvVar2.R;
        pvVar.S = pvVar2.S;
        pvVar.T = pvVar2.T;
        pvVar.U = pvVar2.U;
        pvVar.V = pvVar2.V;
        pvVar.W = pvVar2.W;
        pvVar.X = pvVar2.X;
        pvVar.Y = pvVar2.Y;
        pvVar.Z = pvVar2.Z;
        pvVar.a0 = pvVar2.a0;
        pvVar.b0 = pvVar2.b0;
        pvVar.c0 = pvVar2.c0;
        pvVar.d0 = pvVar2.d0;
        pvVar.e0 = pvVar2.e0;
        pvVar.f0 = pvVar2.f0;
        pvVar.g0 = pvVar2.g0;
        pvVar.h0 = pvVar2.h0;
        pvVar.k0 = pvVar2.k0;
        int[] iArr = pvVar2.i0;
        if (iArr == null || pvVar2.j0 != null) {
            pvVar.i0 = null;
        } else {
            pvVar.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        pvVar.j0 = pvVar2.j0;
        pvVar.l0 = pvVar2.l0;
        pvVar.m0 = pvVar2.m0;
        pvVar.n0 = pvVar2.n0;
        pvVar.o0 = pvVar2.o0;
        qv qvVar = ovVar.c;
        qvVar.getClass();
        qv qvVar2 = this.c;
        qvVar2.getClass();
        qvVar.f863a = qvVar2.f863a;
        qvVar.c = qvVar2.c;
        qvVar.e = qvVar2.e;
        qvVar.d = qvVar2.d;
        rv rvVar = this.b;
        int i = rvVar.f909a;
        rv rvVar2 = ovVar.b;
        rvVar2.f909a = i;
        rvVar2.c = rvVar.c;
        rvVar2.d = rvVar.d;
        rvVar2.b = rvVar.b;
        sv svVar = ovVar.e;
        svVar.getClass();
        sv svVar2 = this.e;
        svVar2.getClass();
        svVar.f956a = svVar2.f956a;
        svVar.b = svVar2.b;
        svVar.c = svVar2.c;
        svVar.d = svVar2.d;
        svVar.e = svVar2.e;
        svVar.f = svVar2.f;
        svVar.g = svVar2.g;
        svVar.h = svVar2.h;
        svVar.i = svVar2.i;
        svVar.j = svVar2.j;
        svVar.k = svVar2.k;
        svVar.l = svVar2.l;
        svVar.m = svVar2.m;
        ovVar.f760a = this.f760a;
        return ovVar;
    }
}
